### ISSUE TITLE
after router.reset() and router.configure() the view isn't updated

### ISSUE THREAD

**Issue by ddittmann** [aurelia/router#237]
I updated the skeleton-navigation from v0.18.1 to v0.19.0.
Try to reconfigure the router with a new map(from server) after authentication. 
It worked in v0.18.1. Now it looks like the router doesn't update the view after router.reset(), router.configure()

I can reproduce this in a fresh skeleton-navigation v0.19.0 by calling
```
reloadRouter(){
    var dynamicMap = [
        { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome' },
        { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users' },
        { route: 'child-router',  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router' }
    ];

    this.router.reset();
    this.router.configure(config => {
        config.map(dynamicMap);
    });    
}
```
Is there something missing to reconfigure the router?

Can I trigger and force the model to update the view?

**Comment by peisenmann** [comment]
@ddittmann Have you tried `this.router._refreshNavigation()`? I believe that has to be called after you reconfigure the router. That being said, it might be worth the team adding a line to `configure` so that it automatically refreshes the navigation.

**Comment by ddittmann** [comment]
```
TypeError: this.router._refreshNavigation is not a function
```
In aurelia-router v0.13 I can find.
```
this.router.refreshNavigation()
```
But I can't see any effect, the navigation view is still empty. Feels like the observation has been canceled.

**Comment by valichek** [comment]
I have similiar problem. Now when `router.reset()` was removed, calling `router.configure(handler)` has no effect if router has been configured already. `handler` is being called. `router.ensureConfigured()` promise is being resolved, but router.routes has no changes. Please, help. My app does really need to re-configure routes when processing auth too.

**Comment by avitex** [comment]
@valichek I am currently in the same boat as you.

**Comment by valichek** [comment]
@avitex Just as an idea, I think we can use `determineActivationStrategy()`, if routes should be reconfigured we return `activationStrategy.replace` in that way we will get new object and get `configureRouter()` called. But to get `determineActivationStrategy()` called we need to refresh the page, can be done with `router.navigate('', {replace: true})`. So when we get new routes, we can get some flag ON and check it in `determineActivationStrategy()`. Have not implement this idea yet, but it looks working for now.

**Comment by avitex** [comment]
@valichek Interesting work around, Ill give it a try at home if I get time. I am currently, and quite embarrassingly so, just calling `document.location.reload()` as a dirty workaround so I could focus on different logic in the application in the meantime.

**Comment by schatekar** [comment]
I am having similar "view not being updated"  experience after I call `this.aurelia.setRoot('authenticated')` where `authenticated.js` contains my router configuration for authenticated routes. Could the root cause for this issue be same?

**Comment by kirandeorespecialprojects** [comment]
I'm facing the same issue when I reset the router with new routes

```
this.router.reset();
      this.router.configure(config => { 
        config.title = 'Aurelia';
        config.map([
          { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome' },
          { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users' },
          { route: 'child-router',  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router' }
        ]);
      }).then(() => { 
        console.log(this.router.routes);
        this.router.navigate('', { replace: true }); 
      });  
```

**Comment by valichek** [comment]
Finally i have implemented my idea for route reset and it works)
```javascript
determineActivationStrategy(){
    return !this.refreshRoutes? activationStrategy.invokeLifecycle : activationStrategy.replace;
}
```
I use `canActivate()` to parse parameters and load new navigation if needed, when navigation is loaded I save it (but not in current VM, bacause it will be re-created) and set `this.refreshRoutes = true` and return `new Redirect(navigationInstruction.fragment+(navigationInstruction.queryString? '?'+navigationInstruction.queryString:''), { replace: true});`

Note that I don't need to set this.refreshRoutes `false`, because when `activationStrategy.replace` is determined, aurelia creates new object for current model.

**Comment by smithaitufe** [comment]
Please @valichek, where is should the determineActivationStrategy method be kept? Is it the main.js folder or each viewmodel that will configure routes dynamically

**Comment by valichek** [comment]
@smithaitufe when you have configureRouter() implemented in viewmodel, you can have  determineActivationStrategy() in that vm too

**Comment by EisenbergEffect** [comment]
You can add `determineActivationStrategy()` to any view model that is navigated to. If you don't want to litter your view model with that, and the strategy is static, you can add an `activationStrategy` property to the route config.
